/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzylogictest;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
/**
 *
 * @author macbookpro
 */
public class FIS_Editor extends javax.swing.JFrame {

       private static int addVCount=1,addOutCount=1;
    private ArrayList<JLabel> inputList= new ArrayList<JLabel>();
    private ArrayList<JLabel> outputList= new ArrayList<JLabel>();
/**
     * Creates new form FIS_Editor
     */
    public FIS_Editor() {
        initComponents();
        this.setLocation(340, 200);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
 // panelDynamic=new JPanel();
     //dynamicPanel.setLayout(new FlowLayout());
    // this.dynamicPanel.add(panelDynamic,BorderLayout.CENTER);

   
    
    

   

    }//GEN-LAST:event_helpBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void jMenu2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenu2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ComponentAdded

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed



    }//GEN-LAST:event_jMenu2ActionPerformed

    private void edit_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_menuActionPerformed
   

    }//GEN-LAST:event_edit_menuActionPerformed

    private void addNewInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewInputActionPerformed
        addVCount++;
        addNewVariableInput(addVCount);


    }//GEN-LAST:event_addNewInputActionPerformed

    private void addNewOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewOutputActionPerformed
          addOutCount++;        
           addNewVariableOutput(addOutCount);

    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIS_Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIS_Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIS_Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIS_Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FIS_Editor().setVisible(true);
            }
            
            
        });
        
          addNewVariableInput(addVCount);
        addNewVariableOutput(addOutCount);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

//METHODS==============================================
   static  JLabel jl;
    private static void addNewVariableInput(final int addVCnt) {
         SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    jl=new JLabel("input"+String.valueOf(addVCnt));
                    dynamicPanelInput.add(jl);
                    dynamicPanelInput.validate();
                    dynamicPanelInput.repaint();
                }
            });
        
    }

    static  JLabel jlO;
    private static void addNewVariableOutput(final int addOCnt) {
         SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    jlO=new JLabel("output"+String.valueOf(addOCnt));
                    jlO.addMouseListener(new MouseAdapter() {
                     public void mouseClicked(MouseEvent e){
                                
                     }
        });
                    
                    dynamicPanelOut.add(jlO);
                    dynamicPanelOut.validate();
                    dynamicPanelOut.repaint();
                }
            });
        
    }
    
   //
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addNewInput;
    private javax.swing.JMenuItem addNewOutput;
    private javax.swing.JComboBox aggregationMethodType;
    private javax.swing.JComboBox andMethodType;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField currentVerblName;
    private javax.swing.JLabel currentVerblRange;
    private javax.swing.JLabel currentVerblType;
    private javax.swing.JComboBox defuzMethodType;
    private static javax.swing.JPanel dynamicPanelInput;
    private static javax.swing.JPanel dynamicPanelOut;
    private javax.swing.JMenuItem edit_menu;
    private javax.swing.JMenu edit_menu2;
    private javax.swing.JLabel fisNameLbl;
    private javax.swing.JLabel fisType;
    private javax.swing.JButton helpBtn;
    private javax.swing.JComboBox implicantMethodType;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox orMethodType;
    // End of variables declaration//GEN-END:variables

   

}
